<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SeleniumJava_ACAEnd-main"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="8.570">
    <properties></properties>

            <testcase
                name="HomeClicked"
                time="0.001"
                classname="Test.LogInTest">

            <failure type="java.lang.NullPointerException" message="Cannot invoke &quot;Page.BasePage.goToMenuItem(String, String, String)&quot; because &quot;this.basePage&quot; is null">
                <![CDATA[java.lang.NullPointerException: Cannot invoke "Page.BasePage.goToMenuItem(String, String, String)" because "this.basePage" is null
                Page.HomePage.goToHomePage(HomePage.java:15)Test.LogInTest.HomeClicked(LogInTest.java:22)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.base/java.lang.reflect.Method.invoke(Method.java:568)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.ArrayList.forEach(ArrayList.java:1511)org.testng.TestRunner.privateRun(TestRunner.java:806)org.testng.TestRunner.run(TestRunner.java:601)org.testng.SuiteRunner.runTest(SuiteRunner.java:433)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)org.testng.SuiteRunner.run(SuiteRunner.java:330)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)org.testng.TestNG.runSuitesLocally(TestNG.java:1176)org.testng.TestNG.runSuites(TestNG.java:1099)org.testng.TestNG.run(TestNG.java:1067)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


            <testcase
                name="BlazeDemoTest"
                time="3.811"
                classname="Test.LogInTest">
            </testcase>
            <testcase
                name="SignUpTest1"
                time="3.098"
                classname="Test.LogInTest">
            </testcase>
            <testcase
                name="Clicked"
                time="1.660"
                classname="Test.LogInTest">
            </testcase>
</testsuite>
